### ISSUE TITLE
Faucet claim

### ISSUE THREAD

**Issue by edy882** [gear-foundation/vara-network#13] opened 2023-09-02 00:59 UTC
### Problem

I have claimed fuacet but not received

### Steps

1.
2.
3.

### Your Substrate Address

13B83uakVFzpwAebbQvqqSZxoJUXRicnuDxZZx6wdzm94gT1

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Kiwi browser

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot_20230901_224747](https://github.com/gear-foundation/vara-network/assets/116999110/7143ed51-28de-4c66-9c01-7b41fc27e650)

**Comment by shamilsan** [comment] 2023-09-05 06:11
Duplicate of #1.

**Closed as completed by shamilsan** 2023-09-05 06:11 UTC
Labels: bug, duplicate, testnet
