### ISSUE TITLE
Minting nft error

### ISSUE THREAD

**Issue by rashadat55** [gear-foundation/vara-network#22] opened 2023-09-02 12:06 UTC
### Problem

Cant mint nft

### Steps

1.
2.
3.
Rpc error

### Expected Behavior

Cant mint nft

### Your Substrate Address

1UMx3jqQKFTefF2jjY6B2dZBZd3MzKMdE13fCjQ4oyPkYU9

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Uploading Screenshot_2023-09-02-15-58-45-376_com.kiwibrowser.browser.jpg…]()

### Notes

Nft mint dont response rpc

**Comment by shamilsan** [comment] 2023-09-05 06:59
Duplicate of #3.

**Closed as not planned by shamilsan** 2023-09-05 06:59 UTC
Labels: bug, duplicate, testnet
