### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Bayunur10** [gear-foundation/vara-network#18] opened 2023-09-02 10:37 UTC
### Problem

I have 70,000 points, I should be ranked number 1 but my website is not on the leaderboard, how do I do this? Subwallet address 5HmTZLK3YtD5CVHxQwkfrw5RGPfmrEGb3tkfYbdohQsxiiF9

### Steps

1.leaderboard
2.the faucet is not accepted even though the claim is successful
3.

### Your Substrate Address

5HmTZLK3YtD5CVHxQwkfrw5RGPfmrEGb3tkfYbdohQsxiiF9

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Other browser

Mises browser

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![Uploading Screenshot_20230902-173629.jpg…]()

**Comment by shamilsan** [comment] 2023-09-05 06:57
Duplicate of #10.

**Closed as not planned by shamilsan** 2023-09-05 06:57 UTC
Labels: bug, duplicate, testnet

**Comment by shamilsan** [comment] 2023-09-11 15:48
I can find you by the address (`0xfc421832dcd0f37f1e66f083af9f1965c3d5c3662ce9e6cc50af40b821258a13`):

![image](https://github.com/gear-foundation/vara-network/assets/66209982/149e0992-00c1-4631-8eb4-79a98904f94a)
