### ISSUE TITLE
cannot mint nft

### ISSUE THREAD

**Issue by n0thing66** [gear-foundation/vara-network#23] opened 2023-09-02 15:32 UTC
### Problem

i can't mint nft

### Steps

1.register
2.faucet
3.min nft
![bug vara network](https://github.com/gear-foundation/vara-network/assets/135194715/e0777d55-4132-485a-9df7-18c9ba4119f6)

### Your Substrate Address

5FLQZXh9grfByZBocZcdNgNGPPAmPfKXVWtpBr1X4Mw1QU6k

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![bug vara network](https://github.com/gear-foundation/vara-network/assets/135194715/af2ae08c-fae9-4de9-a1f1-465487faaa13)

### Notes

please fix his issue

**Comment by shamilsan** [comment] 2023-09-05 06:48
Duplicate of #2.

**Closed as not planned by shamilsan** 2023-09-05 06:48 UTC
Labels: bug, duplicate, testnet
