### ISSUE TITLE
I cant get faucet

### ISSUE THREAD

**Issue by yolgezer55** [gear-foundation/vara-network#30] opened 2023-09-03 08:45 UTC
### Problem

I claimed faucet but it didn't fall into my wallet
![faucet](https://github.com/gear-foundation/vara-network/assets/104051179/141531c7-72fd-4c6e-a1fd-e0cd308dbb18)

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

**Comment by shamilsan** [comment] 2023-09-05 06:45
Duplicate of #1.

**Closed as not planned by shamilsan** 2023-09-05 06:45 UTC
Labels: bug, duplicate, testnet
