### ISSUE TITLE
cannot mint nft

### ISSUE THREAD

**Issue by Nigmamiracle** [gear-foundation/vara-network#33] opened 2023-09-03 10:20 UTC
### Problem

i can't mint nft

### Steps

1.register
2.claim faucet
3.mint nft
4."You are currently not part of the Vara Network Testnet"

### Your Substrate Address

5CCyHgs7C9GmBwWYeVkv3iy2JhhfSft8RaMP9WAJkEfUU9No

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![Screenshot 2023-09-03 171520](https://github.com/gear-foundation/vara-network/assets/88053659/446f0878-f318-467d-bb4b-1b1b72d3d15d)

### Notes

please fix

**Comment by shamilsan** [comment] 2023-09-05 06:42
Duplicate of #2.

**Closed as not planned by shamilsan** 2023-09-05 06:42 UTC
Labels: bug, duplicate, testnet
