### ISSUE TITLE
You are currently not part of the Vara Network Testnet.

### ISSUE THREAD

**Issue by kuncrutt** [gear-foundation/vara-network#28] opened 2023-09-03 04:57 UTC
### Problem

You are currently not part of the Vara Network Testnet.

### Steps

1.I minted a token from faucet
2.it says you are not eligible for nft mint

### Your Substrate Address

5HpviuE98reNYwBNkQBFEZDLmL6928ijdDS7KMvzigfYjUXr

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![vara er](https://github.com/gear-foundation/vara-network/assets/81393360/b731f43c-03f3-4375-aba8-7bdc1c3b858f)

### Notes

please fix it

**Comment by shamilsan** [comment] 2023-09-05 06:47
Duplicate of #2.

**Closed as not planned by shamilsan** 2023-09-05 06:47 UTC
Labels: bug, duplicate, testnet
