### ISSUE TITLE
Cant recieved testnet faucet and not part of vara testnet

### ISSUE THREAD

**Issue by benjoz76** [gear-foundation/vara-network#32] opened 2023-09-03 10:14 UTC
### Problem

have 2 days cant join vara testnet with unclaimed testnet faucet and not part of the testnet while we wanna mint NFTs

### Steps

1.Unclaimed faucet 
2.not part of the testnet
3.

### Your Substrate Address

12bwM5jUfLW6yKYmc9rTxnXSwpZuDhXdnFkp47TXmNpFQJ5K

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![image](https://github.com/gear-foundation/vara-network/assets/111244983/6f36c52d-4039-4b3d-80e6-7418294deb32)

**Comment by shamilsan** [comment] 2023-09-05 06:45
Duplicate of #1 and #2.

**Closed as not planned by shamilsan** 2023-09-05 06:45 UTC
Labels: bug, duplicate, testnet
