### ISSUE TITLE
vara testnet

### ISSUE THREAD

**Issue by hamzatonka41** [gear-foundation/vara-network#11] opened 2023-09-01 22:16 UTC
### Problem

Although I'm in the top ten according to my score, I don't appear in the rankings at all.

### Steps

1.There is a problem with the leaderboard
2.
3.

### Expected Behavior

Sorting and fixing the leaderboard based on real scores

### Your Substrate Address

0xfee22ece316786f35720d132a2a8ffa9e7d88f987d47c70a0e73fc0f7e2d144c

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

file:///C:/Users/Hamza/Pictures/Screenshots/Ekran%20g%C3%B6r%C3%BCnt%C3%BCs%C3%BC%202023-09-02%20011450.png

**Comment by shamilsan** [comment] 2023-09-05 06:10
Duplicate of #10.

**Closed as completed by shamilsan** 2023-09-05 06:10 UTC
Labels: bug, duplicate, testnet

**Comment by shamilsan** [comment] 2023-09-11 15:46
Please try to search again.

![image](https://github.com/gear-foundation/vara-network/assets/66209982/4f90562e-72eb-4653-bfc7-b024c78252b1)
