### ISSUE TITLE
Leaderboard issue

### ISSUE THREAD

**Issue by lavenil444** [gear-foundation/vara-network#39] opened 2023-09-04 17:19 UTC
### Problem

I had 17.9k point but I cant see my self on leaderboard. I'm not visible 
![image](https://github.com/gear-foundation/vara-network/assets/110575391/75806257-24d7-40e8-917d-29fb5591be8f)
![image](https://github.com/gear-foundation/vara-network/assets/110575391/20b13c12-b2dc-44da-bf6e-5c522d90a282)

### Steps

1. I check leaderboard status
2. Searching my name
3. I cant find my name

### Your Substrate Address

4aDtQGtt44Hhjgf2kMogXmr8tYstywXAFzUaBNkkrFxPD2KL

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Opera

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![image](https://github.com/gear-foundation/vara-network/assets/110575391/75806257-24d7-40e8-917d-29fb5591be8f)
![image](https://github.com/gear-foundation/vara-network/assets/110575391/20b13c12-b2dc-44da-bf6e-5c522d90a282)

**Comment by shamilsan** [comment] 2023-09-05 06:12
Duplicate of #10.

**Closed as completed by shamilsan** 2023-09-05 06:12 UTC
Labels: bug, duplicate, testnet

**Comment by shamilsan** [comment] 2023-09-11 15:45
Try search you by the address: `0xce884d3edba238adc93897846bfb114602c9ced6aab4b54c091a4023ca0edc40`

![image](https://github.com/gear-foundation/vara-network/assets/66209982/200bd289-8197-4c27-98ac-f3c887334df5)

**Comment by lavenil444** [comment] 2023-09-14 21:22
> Try search you by the address: `0xce884d3edba238adc93897846bfb114602c9ced6aab4b54c091a4023ca0edc40`
> 
> ![image](https://user-images.githubusercontent.com/66209982/267074903-200bd289-8197-4c27-98ac-f3c887334df5.png)

thank you for your replie, the only problem is now my point is not true. I had +25k point but it says 9k
