### ISSUE TITLE
Faucet claim failed

### ISSUE THREAD

**Issue by irman1996** [gear-foundation/vara-network#31] opened 2023-09-03 08:58 UTC
### Problem

I requested faucet, but its didnt come

### Steps

1.
2.
3.

### Your Substrate Address

5EnDNL75NG3x7bUxX4iQ3c2pppvee8GeFZT2eK44zYwjjHE6

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot_202](https://github.com/gear-foundation/vara-network/assets/55221851/561e66ce-e0c5-48a3-8e03-50f1a4172a11)

**Comment by shamilsan** [comment] 2023-09-05 06:43
Duplicate of #1.

**Closed as not planned by shamilsan** 2023-09-05 06:43 UTC
Labels: bug, duplicate, testnet
