### ISSUE TITLE
Cannot claim faucet

### ISSUE THREAD

**Issue by blntbytk** [gear-foundation/vara-network#38] opened 2023-09-04 11:42 UTC
### Problem

when i hit the get tetsnet balance had an error window but it is empty
<img width="942" alt="xx11" src="https://github.com/gear-foundation/vara-network/assets/105415280/63c56bec-b1eb-4a77-9be2-413b2d83a7b8">

### Steps

1.
2.
3.

### Your Substrate Address

0x2863060f2f197b01078525e72462aeb4681316a6f7696c015fb3aabb589bd64a

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

<img width="942" alt="xx11" src="https://github.com/gear-foundation/vara-network/assets/105415280/8d82f0f7-2ee4-4d4b-b6b1-5a154059dc7a">

**Comment by blntbytk** [comment] 2023-09-04 11:45
5CyfBu7ikHSbCQHZ6cW5usHYrn2rLk3WD7dgjwGY1AfdByLR

**Comment by shamilsan** [comment] 2023-09-05 06:15
Duplicate of #1.

**Closed as completed by shamilsan** 2023-09-05 06:15 UTC
Labels: bug, duplicate, testnet
