### ISSUE TITLE
I cant mint an nft

### ISSUE THREAD

**Issue by yolgezer55** [gear-foundation/vara-network#29] opened 2023-09-03 08:40 UTC
### Problem

I cant mint an nft 
![Ekran görüntüsü 2023-09-03 113757](https://github.com/gear-foundation/vara-network/assets/104051179/3a6140f3-4bb8-4011-8318-b5f00e777129)

### Steps

1.Enter Activities
2.Mint an Nft
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Ekran görüntüsü 2023-09-03 113757](https://github.com/gear-foundation/vara-network/assets/104051179/5efca4ed-fb5d-473b-8790-cfed5e955cdf)

**Comment by shamilsan** [comment] 2023-09-05 06:43
Duplicate of #2.

**Closed as not planned by shamilsan** 2023-09-05 06:43 UTC
Labels: bug, duplicate, testnet
