### ISSUE TITLE
Mint nft error

### ISSUE THREAD

**Issue by anaraydinli55** [gear-foundation/vara-network#19] opened 2023-09-02 11:21 UTC
### Problem

Can't mint nft via polkadot wallet, polkadot wallet  don't response for sing in

### Steps

1.
2.
3.
Don't response polkadot wallet

### Expected Behavior

Rpc not response 

### Your Substrate Address

1spkNSiGp6HTTtMHyDw75CN6UQNv6V1PamhToboXJtC9V7h

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

#17 

### Notes

Can't use faucet too

**Comment by shamilsan** [comment] 2023-09-05 06:52
Duplicate of #2.

**Closed as not planned by shamilsan** 2023-09-05 06:52 UTC
Labels: bug, duplicate, testnet
