### ISSUE TITLE
Can't mint nft

### ISSUE THREAD

**Issue by anaraydinli55** [gear-foundation/vara-network#20] opened 2023-09-02 11:30 UTC
### Problem

Nft mint error

### Steps

1.
2.
3.
Get issue by minting, not response 

### Expected Behavior

Not response

### Your Substrate Address

12TSHgCkBaBpM1m1qUrkcvRRQaacm7aYm3D8n9pEZJhK314A

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot_20230902_152749](https://github.com/gear-foundation/vara-network/assets/109851305/68ec9779-9930-41cb-ab72-55b7b5ce95ab)

### Notes

I get error by claim test tokens too

**Comment by shamilsan** [comment] 2023-09-05 06:59
Duplicate of #3.

**Closed as not planned by shamilsan** 2023-09-05 06:59 UTC
Labels: bug, duplicate, testnet
