### ISSUE TITLE
Faucet Bug

### ISSUE THREAD

**Issue by CriptoNite** [gear-foundation/vara-network#15] opened 2023-09-02 01:18 UTC
### Problem

I claimed my faucet tokens but the U/I show 0.0 as my Balance 

### Steps

1.claimed faucet rewards
2.transaction pass
3. balance shows 0.0 of value

### Expected Behavior

get the faucet tokens

### Your Substrate Address

5DnzfKxC2djbkMR6XbTgw88vVPTMRVuynUxf9nmGH7EkSFat

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Brave

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

<img width="959" alt="image" src="https://github.com/gear-foundation/vara-network/assets/143854344/e9bebff1-f43f-486d-9d00-467fc66f9108">

**Comment by shamilsan** [comment] 2023-09-05 06:48
Duplicate of #1.

**Closed as not planned by shamilsan** 2023-09-05 06:48 UTC
Labels: bug, duplicate, testnet
