### ISSUE TITLE
Faucet eror

### ISSUE THREAD

**Issue by Iqbal1998** [gear-foundation/vara-network#35] opened 2023-09-04 03:35 UTC
### Problem

Balance and faucet errors have been claimed but are still zero

### Steps

1.
2.
3.

### Your Substrate Address

0x7001a77a38ebd5e296186b75626b2745246b83087e4fb709f6c4b1056b354626

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Mises

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![Screenshot_20230904-103450_Kiwi Browser](https://github.com/gear-foundation/vara-network/assets/91222625/0d24190e-bf79-4f80-941f-854ef4c9d7cd)

**Comment by shamilsan** [comment] 2023-09-05 06:18
Duplicate of #1.

**Closed as not planned by shamilsan** 2023-09-05 06:18 UTC
Labels: bug, duplicate, testnet
