### ISSUE TITLE
Faucet claim issue

### ISSUE THREAD

**Issue by brkcnr** [gear-foundation/vara-network#17] opened 2023-09-02 08:26 UTC
### Problem

I collected all of my tokens yesterday but still didn't receive any.

### Steps

1. Register
2. Connect the wallet
3. Collect faucet token

### Expected Behavior

I've expected to claim my tokens easily.

### Your Substrate Address

5ELLnrhi7G9DaeXG7eFnTxyLVKrZgmnCeWBTw8F8F31dr6vW

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Ekran görüntüsü 2023-09-02 112527](https://github.com/gear-foundation/vara-network/assets/92725873/fbed58db-5a86-450a-93a3-a0c35053be16)

**Comment by shamilsan** [comment] 2023-09-05 06:51
Duplicate of #1.

**Closed as not planned by shamilsan** 2023-09-05 06:51 UTC
Labels: bug, duplicate, testnet
