### ISSUE TITLE
Cant mint nft

### ISSUE THREAD

**Issue by Skeomorph** [gear-foundation/vara-network#26] opened 2023-09-02 21:42 UTC
### Problem

i cant mitn nft!

### Steps

1.Register
2.Activities
3.use Mint an NFT

### Your Substrate Address

5Cng5LF35yfgFyDjrPn6caVP5AkLLsijuvgYFfR5s3t62z5i

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot_2](https://github.com/gear-foundation/vara-network/assets/142544007/2df924ca-69a2-4a22-8104-2d1d9a0f05de)

### Notes

fix pls

**Comment by shamilsan** [comment] 2023-09-05 06:54
Duplicate of #2.

**Closed as not planned by shamilsan** 2023-09-05 06:54 UTC
Labels: bug, duplicate, testnet
