### ISSUE TITLE
Faucet claim

### ISSUE THREAD

**Issue by crtexpert** [gear-foundation/vara-network#8] opened 2023-09-01 16:00 UTC
### Problem

I have clicked claim faucet button after registered. I had 1 available claim and after i clickd the button my available claim reduce to 0 but no tVARA received. 

5EExSKnZV9zF4QFTTA29zTcwE6UPs8LDo2P2myVi44ZnDQhw This is the wallet address .

### Steps

1.Register
2.Go to faucet page.
3.Click claim.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [X] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![ö](https://github.com/gear-foundation/vara-network/assets/55183922/18d02efb-700a-49b2-88f3-e22b4f948859)

**Comment by shamilsan** [comment] 2023-09-04 07:38
Duplicate of #1.

**Closed as completed by shamilsan** 2023-09-04 07:38 UTC
Labels: bug, duplicate, testnet
