### ISSUE TITLE
Faucet issue

### ISSUE THREAD

**Issue by dev010101001** [gear-foundation/vara-network#16] opened 2023-09-02 07:13 UTC
### Problem

After registration and claiming faucet, i get message: "You are currently not part of the Vara Network Testnet." on page: [nft.vara-network.io](https://nft.vara-network.io/list?node=wss%3A%2F%2Fvit.vara-network.io&master=0x9a8d7a221dcfbe21d140a43f4c7f4c87ee54f331992effdd9d8ab9bd54951c3d)

### Steps

1. Register in incentivized testnet
2. Go to page https://nft.vara-network.io/list?node=wss%3A%2F%2Fvit.vara-network.io&master=0x9a8d7a221dcfbe21d140a43f4c7f4c87ee54f331992effdd9d8ab9bd54951c3d
3. Get the error

### Expected Behavior

I expect to see my NFT in this page, Also i expect to see test tokens i claimed in faucet

### Your Substrate Address

5HGckRKN9GGLhAjvaRjiZvTSnL1mtW7MSjsAsfdmgsDCbYoF

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![image](https://github.com/gear-foundation/vara-network/assets/88091949/780318d7-86ba-45a9-b682-d05816d6dca3)
![image](https://github.com/gear-foundation/vara-network/assets/88091949/dbd3fa01-274e-4bf2-a129-0aef442a3189)

**Comment by shamilsan** [comment] 2023-09-05 06:49
Duplicate of #1 and #2.

**Closed as not planned by shamilsan** 2023-09-05 06:49 UTC
Labels: bug, duplicate, testnet
